# Generated by Django 2.1 on 2020-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='catalogue',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
